# Generated by Django 5.0 on 2023-12-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres_usuario', models.CharField(max_length=200, verbose_name='Nombre(s)')),
                ('appat_usuario', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apmat_usuario', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('num_tel', models.BigIntegerField(verbose_name='Número telefónico')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('rol', models.IntegerField(choices=[(2, 'Soporte'), (3, 'Usuario')], verbose_name='Rol')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.CharField(max_length=50, verbose_name='Almacen')),
                ('factura', models.CharField(max_length=50, verbose_name='Factura')),
                ('serie', models.CharField(max_length=1, verbose_name='Serie')),
                ('rfc', models.CharField(max_length=14, verbose_name='RFC')),
                ('UUID', models.TextField(verbose_name='UUID')),
                ('FechaDeTimbrado', models.CharField(max_length=500, verbose_name='Fecha de timbrado')),
                ('RutaProduccion', models.CharField(max_length=500, verbose_name='Ruta Producción')),
                ('RutaAppFact', models.CharField(max_length=500, verbose_name='RutaAppFact')),
            ],
        ),
    ]
