# Generated by Django 5.0 on 2023-12-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
