# Generated by Django 4.2.8 on 2023-12-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facturas',
            new_name='Factura',
        ),
    ]
