# Generated by Django 4.2.8 on 2023-12-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresor', '0002_rename_facturas_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='RutaAppFact',
            field=models.TextField(verbose_name='Ruta app'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='RutaProduccion',
            field=models.TextField(verbose_name='Ruta producción'),
        ),
    ]
