# Generated by Django 5.0 on 2023-12-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compresor', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.CharField(max_length=50, verbose_name='Almacen')),
                ('factura', models.CharField(max_length=50, verbose_name='Factura')),
                ('serie', models.CharField(max_length=1, verbose_name='Serie')),
                ('rfc', models.CharField(max_length=14, verbose_name='RFC')),
                ('UUID', models.TextField(verbose_name='UUID')),
                ('FechaDeTimbrado', models.CharField(max_length=500, verbose_name='Fecha de timbrado')),
                ('RutaProduccion', models.CharField(max_length=500, verbose_name='Ruta Producción')),
                ('RutaAppFact', models.CharField(max_length=500, verbose_name='RutaAppFact')),
            ],
        ),
    ]
